# Write your code here :-)
print("Enter the first number to add:")
first = input()
print("Enter the second number to add:")
second = input()
print("Enter the third number to add:")
third = input()
print("The sums is " + first + second + third)
